/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * Repository defaults are set for GitHub Pages, and can still be replaced
 * by CI if placeholder injection is used in the future.
 */

const DATA_CONFIG = {
    repoOwner: 'ttaohe',
    repoName: 'daily-arXiv-ai-enhanced',
    dataBranch: 'data',

    getDataBaseUrl: function() {
        return `https://raw.githubusercontent.com/${this.repoOwner}/${this.repoName}/${this.dataBranch}`;
    },

    getDataUrl: function(filePath) {
        if (
            window.location.hostname === 'localhost' ||
            window.location.hostname === '127.0.0.1' ||
            window.location.hostname.startsWith('192.168.') ||
            window.location.hostname.startsWith('43.')
        ) {
            return filePath;
        }
        return `${this.getDataBaseUrl()}/${filePath}`;
    }
};
