/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The repository information is injected during the CI/CD build process
 * to enable fetching data from the data branch.
 */

const DATA_CONFIG = {
    repoOwner: 'PLACEHOLDER_REPO_OWNER',
    repoName: 'PLACEHOLDER_REPO_NAME',
    dataBranch: 'data',

    getDataBaseUrl: function() {
        return `https://raw.githubusercontent.com/${this.repoOwner}/${this.repoName}/${this.dataBranch}`;
    },

    getDataUrl: function(filePath) {
        if (
            window.location.hostname === 'localhost' ||
            window.location.hostname === '127.0.0.1' ||
            window.location.hostname.startsWith('192.168.') ||
            window.location.hostname.startsWith('43.')
        ) {
            return filePath;
        }
        return `${this.getDataBaseUrl()}/${filePath}`;
    }
};
